# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Work\Python\PyQt5\PyQt5_FESTO\QMainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menuBar.setObjectName("menuBar")
        self.menuData = QtWidgets.QMenu(self.menuBar)
        self.menuData.setObjectName("menuData")
        self.menuWork = QtWidgets.QMenu(self.menuBar)
        self.menuWork.setObjectName("menuWork")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.action11_CSV_File_To_Excel = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/CSV_Excel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action11_CSV_File_To_Excel.setIcon(icon)
        self.action11_CSV_File_To_Excel.setObjectName("action11_CSV_File_To_Excel")
        self.action12_Merge_FESTO_Files = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/MergeExcel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action12_Merge_FESTO_Files.setIcon(icon1)
        self.action12_Merge_FESTO_Files.setObjectName("action12_Merge_FESTO_Files")
        self.action21_Help = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("images/Help.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action21_Help.setIcon(icon2)
        self.action21_Help.setObjectName("action21_Help")
        self.action22_About = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("images/about.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action22_About.setIcon(icon3)
        self.action22_About.setObjectName("action22_About")
        self.action13_Mapping = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("images/Mapping.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action13_Mapping.setIcon(icon4)
        self.action13_Mapping.setObjectName("action13_Mapping")
        self.action14_Summary = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("images/Summary.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action14_Summary.setIcon(icon5)
        self.action14_Summary.setObjectName("action14_Summary")
        self.action15_Merge_Invoice = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("images/Merge1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action15_Merge_Invoice.setIcon(icon6)
        self.action15_Merge_Invoice.setObjectName("action15_Merge_Invoice")
        self.action16_Append_Invoice_to_Summary = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("images/Merge2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action16_Append_Invoice_to_Summary.setIcon(icon7)
        self.action16_Append_Invoice_to_Summary.setObjectName("action16_Append_Invoice_to_Summary")
        self.action17_Get_Unit_Prices_Style_1 = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("images/UnitPrice1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action17_Get_Unit_Prices_Style_1.setIcon(icon8)
        self.action17_Get_Unit_Prices_Style_1.setObjectName("action17_Get_Unit_Prices_Style_1")
        self.action18_Get_Unit_Prices_Style_2 = QtWidgets.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("images/UnitPrices2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action18_Get_Unit_Prices_Style_2.setIcon(icon9)
        self.action18_Get_Unit_Prices_Style_2.setObjectName("action18_Get_Unit_Prices_Style_2")
        self.action19_Compute_Tickets_Price = QtWidgets.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("images/Report.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action19_Compute_Tickets_Price.setIcon(icon10)
        self.action19_Compute_Tickets_Price.setObjectName("action19_Compute_Tickets_Price")
        self.actionExit = QtWidgets.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("images/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon11)
        self.actionExit.setObjectName("actionExit")
        self.menuData.addAction(self.action11_CSV_File_To_Excel)
        self.menuData.addAction(self.action12_Merge_FESTO_Files)
        self.menuData.addAction(self.action13_Mapping)
        self.menuData.addAction(self.action14_Summary)
        self.menuData.addAction(self.action15_Merge_Invoice)
        self.menuData.addAction(self.action16_Append_Invoice_to_Summary)
        self.menuData.addAction(self.action17_Get_Unit_Prices_Style_1)
        self.menuData.addAction(self.action18_Get_Unit_Prices_Style_2)
        self.menuData.addAction(self.action19_Compute_Tickets_Price)
        self.menuData.addSeparator()
        self.menuData.addAction(self.actionExit)
        self.menuWork.addAction(self.action21_Help)
        self.menuWork.addAction(self.action22_About)
        self.menuBar.addAction(self.menuData.menuAction())
        self.menuBar.addAction(self.menuWork.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuData.setTitle(_translate("MainWindow", "Work"))
        self.menuWork.setTitle(_translate("MainWindow", "Help"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.action11_CSV_File_To_Excel.setText(_translate("MainWindow", "1.CSV File To Excel"))
        self.action12_Merge_FESTO_Files.setText(_translate("MainWindow", "2.Merge FESTO Files"))
        self.action21_Help.setText(_translate("MainWindow", "Help"))
        self.action22_About.setText(_translate("MainWindow", "About"))
        self.action13_Mapping.setText(_translate("MainWindow", "3.Mapping"))
        self.action14_Summary.setText(_translate("MainWindow", "4.Summary"))
        self.action15_Merge_Invoice.setText(_translate("MainWindow", "5.Merge Invoice"))
        self.action16_Append_Invoice_to_Summary.setText(_translate("MainWindow", "6.Append Invoice to Summary"))
        self.action17_Get_Unit_Prices_Style_1.setText(_translate("MainWindow", "7.Get Unit Prices Style 1 "))
        self.action18_Get_Unit_Prices_Style_2.setText(_translate("MainWindow", "8.Get Unit Prices Style 2"))
        self.action19_Compute_Tickets_Price.setText(_translate("MainWindow", "9.Compute Tickets Price"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

