# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Work\Python\PyQt5\PyQt5_FESTO\SubForm9_MakeReport.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(755, 283)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        Form.setFont(font)
        self.btn_Process = QtWidgets.QPushButton(Form)
        self.btn_Process.setGeometry(QtCore.QRect(240, 190, 101, 41))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.btn_Process.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/btn_ok.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_Process.setIcon(icon)
        self.btn_Process.setObjectName("btn_Process")
        self.btn_Exit = QtWidgets.QPushButton(Form)
        self.btn_Exit.setGeometry(QtCore.QRect(410, 190, 101, 41))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.btn_Exit.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/btn_Exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_Exit.setIcon(icon1)
        self.btn_Exit.setObjectName("btn_Exit")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(30, 30, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.btn_Browse = QtWidgets.QPushButton(Form)
        self.btn_Browse.setGeometry(QtCore.QRect(640, 30, 101, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.btn_Browse.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("images/btn_File_Browser.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_Browse.setIcon(icon2)
        self.btn_Browse.setObjectName("btn_Browse")
        self.txt_SummaryFile = QtWidgets.QPlainTextEdit(Form)
        self.txt_SummaryFile.setGeometry(QtCore.QRect(126, 30, 505, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txt_SummaryFile.setFont(font)
        self.txt_SummaryFile.setPlainText("")
        self.txt_SummaryFile.setObjectName("txt_SummaryFile")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(30, 70, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.txt_PriceFile = QtWidgets.QPlainTextEdit(Form)
        self.txt_PriceFile.setGeometry(QtCore.QRect(126, 73, 505, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txt_PriceFile.setFont(font)
        self.txt_PriceFile.setPlainText("")
        self.txt_PriceFile.setObjectName("txt_PriceFile")
        self.btn_Browse_2 = QtWidgets.QPushButton(Form)
        self.btn_Browse_2.setGeometry(QtCore.QRect(640, 80, 101, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.btn_Browse_2.setFont(font)
        self.btn_Browse_2.setIcon(icon2)
        self.btn_Browse_2.setObjectName("btn_Browse_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(30, 107, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.cbo_Country = QtWidgets.QComboBox(Form)
        self.cbo_Country.setGeometry(QtCore.QRect(128, 116, 171, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cbo_Country.setFont(font)
        self.cbo_Country.setObjectName("cbo_Country")
        self.cbo_Period = QtWidgets.QComboBox(Form)
        self.cbo_Period.setGeometry(QtCore.QRect(460, 114, 171, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cbo_Period.setFont(font)
        self.cbo_Period.setObjectName("cbo_Period")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(370, 104, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Step 9 Make Report"))
        self.btn_Process.setText(_translate("Form", "Process"))
        self.btn_Exit.setText(_translate("Form", "Exit"))
        self.label.setText(_translate("Form", "Summary File:"))
        self.btn_Browse.setText(_translate("Form", " Browse"))
        self.label_2.setText(_translate("Form", "Unit Price File:"))
        self.btn_Browse_2.setText(_translate("Form", " Browse"))
        self.label_3.setText(_translate("Form", "Select Country:"))
        self.label_4.setText(_translate("Form", "Select Period:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

